export { default as userRoutes } from './userRoutes'
export { default as categoryRoutes } from './categoryRoutes'
export { default as productRoutes } from './productRoutes'
export { default as addressRoutes } from './addressRoutes'
export { default as orderRoutes } from './orderRoutes'
